services:
  fsw:
    image: "fsw"
#    command: "sleep infinity"  # Useful for debugging
    command: ["/bin/bash", "-c", "/code/./script_delay_with_sudo.sh 10.5.0.2 650 && ./core-cpu4"]
    environment:
      - DISPLAY=${DISPLAY}
      - QT_X11_NO_MITSHM=1
    sysctls:
      - fs.mqueue.msg_max=64
    networks:
      spaceip:
        ipv4_address: 10.5.0.3
    privileged: true
    cap_add:
      - NET_ADMIN
    cap_drop:
      - ALL        
    build:
      context: ../../
      dockerfile: cfs/Dockerfile
      target: "fsw"
      args:
        - USER_UID=${UID:-1000}
    volumes:
      - "/tmp/.X11-unix:/tmp/.X11-unix:rw"
      - "${XAUTHORITY:-$HOME/.Xauthority}:/root/.Xauthority:rw"
    working_dir: /code/cFS/build/exe/cpu4

  yamcs:
    image: "yamcs"
#    command: "sleep infinity"  # Useful for debugging
    command: ["/bin/bash", "-c", "/rosws/./script_delay.sh 10.5.0.3 650 && mvn yamcs:run"]
    environment:
      - DISPLAY=${DISPLAY}
      - QT_X11_NO_MITSHM=1
    networks:
      spaceip:
        ipv4_address: 10.5.0.2
    privileged: true
    cap_add:
      - NET_ADMIN
    cap_drop:
      - ALL        
    build:
      context: ../../
      dockerfile: yamcs/Dockerfile
    volumes:
      - "/tmp/.X11-unix:/tmp/.X11-unix:rw"
      - "${XAUTHORITY:-$HOME/.Xauthority}:/root/.Xauthority:rw"

  rosfsw:
    image: "rosws"
    #command: "sleep infinity"  # Useful for debugging
    command: ["/bin/bash", "-c", "source install/setup.bash && ros2 launch dragoman_fsw_sim lunar_exploration_flight_demo.launch.py cfs_ip:=10.5.0.3 robot_ip:=10.5.0.4"]
    environment:
      - ROS_AUTOMATIC_DISCOVERY_RANGE=LOCALHOST
      - DISPLAY=${DISPLAY}
      - QT_X11_NO_MITSHM=1
    networks:
      spaceip:
        ipv4_address: 10.5.0.4
    build:
      context: ../../
      dockerfile: rosws/Dockerfile
    volumes:
      - "/dev/dri:/dev/dri"
      - "/tmp/.X11-unix:/tmp/.X11-unix:rw"
      - "${XAUTHORITY:-$HOME/.Xauthority}:/root/.Xauthority:rw"

  rosgsw:
    image: "rosws"
    #command: "sleep infinity"  # Useful for debugging
    command: ["/bin/bash", "-c", "source install/setup.bash && ros2 launch dragoman_ground_example lunar_exploration_ground.launch.py yamcs_url:=10.5.0.2:8090 yamcs_ip:=10.5.0.2"]
    environment:
      - ROS_AUTOMATIC_DISCOVERY_RANGE=LOCALHOST
      - DISPLAY=${DISPLAY}
      - QT_X11_NO_MITSHM=1
    networks:
      spaceip:
        ipv4_address: 10.5.0.6
    build:
      context: ../../
      dockerfile: rosws/Dockerfile
    volumes:
      - "/dev/dri:/dev/dri"
      - "/tmp/.X11-unix:/tmp/.X11-unix:rw"
      - "${XAUTHORITY:-$HOME/.Xauthority}:/root/.Xauthority:rw"

networks:
  spaceip:
    driver: bridge
    ipam:
      config:
        - subnet: 10.5.0.0/16
          gateway: 10.5.0.1
