services:
  fsw:
    image: "fsw-dev"
    #command: "sleep infinity"  # Useful for debugging
    command: "./core-cpu2"
    environment:
      - DISPLAY=novnc:0.0
    sysctls:
      - fs.mqueue.msg_max=64
    networks:
      spaceip:
        ipv4_address: 10.5.0.3
    build:
      context: .
      dockerfile: fsw.Dockerfile
      target: "fsw-dev"
      args:
        - USER_UID=${UID:-1000}
    volumes:
      - "./cFS:/code/cFS"
      - "./edoras_core:/code/edoras_core"
    working_dir: /code/cFS/build/exe/cpu2

  yamcs:
    image: "yamcs"
    #command: "sleep infinity"  # Useful for debugging
    command: ["mvn", "yamcs:run"]
    environment:
      - DISPLAY=novnc:0.0
    networks:
      spaceip:
        ipv4_address: 10.5.0.2
    build:
      context: .
      dockerfile: yamcs.Dockerfile

  rosfsw:
    image: "rosws"
    #command: "sleep infinity"  # Useful for debugging
    command: ["/bin/bash", "-c", "source install/setup.bash && ros2 launch dragoman_fsw_sim gateway_single_arm_flight_demo_multihost.launch.py"]
    environment:
      - ROS_AUTOMATIC_DISCOVERY_RANGE=LOCALHOST
      - DISPLAY=novnc:0.0
    networks:
      spaceip:
        ipv4_address: 10.5.0.4
    build:
      context: .
      dockerfile: rosws.Dockerfile

  novnc:
    image: theasp/novnc:latest
    environment:
      - DISPLAY_WIDTH=1920
      - DISPLAY_HEIGHT=1080
      - RUN_XTERM=no
    ports:
      - "8080:8080"
    networks:
      spaceip:
        ipv4_address: 10.5.0.5

networks:
  spaceip:
    driver: bridge
    ipam:
      config:
        - subnet: 10.5.0.0/16
          gateway: 10.5.0.1
